# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKpUX-X95gIULNvcuM_MId7Nx9s5CdOu
"""

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("1.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

import cv2
from google.colab.patches import cv2_imshow


rasm = cv2.imread("1.jpg")
cv2_imshow(rasm)

from google.colab.patches import cv2_imshow
import cv2
rasm2=cv2.imread("sam.jpg")
cv2_imshow(rasm2)

oqqora1=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora1)

import cv2
from google.colab.patches import cv2_imshow


rasm2 = cv2.imread("sam.jpg")
cv2_imshow(rasm2)

from google.colab.patches import cv2_imshow
import cv2
rasm3=cv2.imread("bcat.jpg")
cv2_imshow(rasm3)

oqqora2=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora2)

import cv2
from google.colab.patches import cv2_imshow


rasm3 = cv2.imread("bcat.jpg")
cv2_imshow(rasm3)